name: sws
recipe: drupal8
config:
  php: '8.2'
  via: nginx
  webroot: web
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://sws.lndo.site"
  pma:
    type: phpmyadmin
  node:
    type: node
    globals:
      gulp-cli: "latest"
tooling:
  node:
    service: 'node'
  npm:
    service: 'node'
  gulp:
    service: 'node'
    cmd:
      - 'cd /app/web/themes/custom/southernwall && npx gulp'
